### ISSUE TITLE
Script does not find jq when testing hash

### ISSUE THREAD

**Issue by biofool** [samrocketman/docker-compose-ha-consul-vault-ui#9]
On DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

sha256sum is /usr/bin/sha256sum
+ sha256sum -c -
sha256sum: jq: No such file or directory
jq: FAILED open or read

**Comment by samrocketman** [comment]
Did you bootstrap the binaries first?  See https://github.com/samrocketman/docker-compose-ha-consul-vault-ui#start-the-cluster

I primarily develop on Ubuntu 18.04 but can test with Vagrant.

**Comment by samrocketman** [comment]
# Cannot reproduce

I verified with Vagrant that this project requires no extra modifications to support the new Ubuntu release.

At the root of the repository I ran the following code:

```
vagrant init ubuntu/focal64
vagrant up
vagrant ssh
```
I set up the VM.
```
cd ~
mkdir git
cd git
git clone https://github.com/samrocketman/home
cd home
./setup.sh
~/bin/install-docker-compose.sh
```

I installed Docker and started it following the [official Docker for Ubuntu guide](https://docs.docker.com/engine/install/ubuntu/).
```
sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io
sudo usermod -a -G docker vagrant
sudo systemctl start docker.service
```

I logged out and logged back into vagrant with `vagrant ssh` so that the group settings applied.  I installed `unzip` which is a prerequisite to this project.  I also needed to do a symlink hack for vagrant.  Please note this project assumes (as noted in the README) that it was cloned to `$HOME/git/github/docker-compose-ha-consul-vault-ui`.

```
sudo apt install unzip
ln -s /vagrant /home/vagrant/git/github/docker-compose-ha-consul-vault-ui
```

Finally, I started the project according to the README.

```
./scripts/consul-agent.sh --bootstrap
docker-compose up -d
./scripts/initialize-vault.sh
```

I was even able to test logging into Vault by port forwarding the SOCKS proxy.

```
vagrant ssh-config > /tmp/config
ssh -F /tmp/config -vNL 127.0.0.1:1080:127.0.0.1:1080 default
```

I configured my browser with the SOCKS proxy according to the README and successfully browsed to http://consul.service.consul:8500

Here's a screenshot of it running with `Ubuntu 20.04.1 LTS`.

![Screenshot from 2020-11-14 00-34-49](https://user-images.githubusercontent.com/875669/99140609-522e5600-2611-11eb-8b73-31d919fcd83b.png)
